### ISSUE TITLE
Suicide killed the meter

### ISSUE THREAD

**Issue by Nessiesson** [NarcolepticFrog/RedstoneMultimeter#3] opened 2018-06-03 05:35 UTC
Using RSMM v0.5-1.12.0.

If you `/kill` yourself, any meters you put down client-side don't show up, and existing meters will stop updating. In both instances, relogging fixes it. #

**Comment by NarcolepticFrog** [comment] 2018-06-03 15:25
Before I forget, the cause of this bug is that when players return from the end or respawns, `PlayerList.recreatePlayerEntity` is called to create a new `EntityPlayerMP` instance for the player. Since plugin channel subscriptions are stored in the entity, they are lost when this happens.

Two possible fixes:
1. Modify `recreatePlayerEntity` to also copy the plugin channel subscription set.
2. Move subscription information into `PlayerList`.

This bug also certainly affects the carpet implementation of the RSMM server and should be fixed there too.

**Closed as completed** 2018-06-16 15:55 UTC
